M48
; DRILL file {KiCad (7.0.0)} date Mon Sep 11 13:22:19 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-11T13:22:19+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X0.7247Y-4.2151
X0.7248Y-1.0716
X10.9019Y-1.072
X10.9023Y-4.2144
T0
M30
